In [2]:
# Question 1 : Create a null vector of size 10 but the fifth value which is 1.

In [3]:
import numpy as np

In [7]:
vector = np.zeros(10)
vector[4] =1
print(vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
# Ques2:  Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [10]:
a = int(input("Enter the first number"))
b = int(input("Enter the second number"))
array = np.random.rand(a,b)
print(array)
average =  np.mean(array)

[[0.29007544 0.24477272 0.66750815 0.0981207 ]
 [0.95037007 0.52527046 0.86815056 0.46316896]
 [0.14487213 0.58114234 0.2598336  0.56561099]]


In [11]:
# Ques3:Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

In [12]:
def border_array(a, b):
    array = np.ones((a, b), dtype=int)
    array[1:-1, 1:-1] = 0
    return array

# Example usage:
a = 5
b = 6
result = border_array(a, b)
print("2D array with 1 on the border and 0 inside:")
print(result)


2D array with 1 on the border and 0 inside:
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [16]:
# Question 4 :  Create a vector of size 10 with values ranging from 0 to 1, both excluded
vector = np.random.uniform(low=0.00001, high=0.99999, size=10)
print(vector)

[0.89686278 0.5509803  0.79499925 0.44217655 0.28982185 0.93430678
 0.19542652 0.86935122 0.58765989 0.0773828 ]


In [19]:
#Question 5 : Can you create a identity mattrix of shape (3,4). If yes write code for it.
# NO 

In [21]:
#Question 6 : Create a 5x5 matrix with row values ranging from 0 to 4.
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [24]:
# Question 7: Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.
coordinates = np.random.randint(1,101, size = (10,2))
point = np.array([2,3]) 
distances = np.linalg.norm(coordinates - point, axis=1)
distance_array = distances.astype(int)
print(coordinates)
print(point)
print(distance_array)

[[99 56]
 [81 98]
 [69 43]
 [82 54]
 [27  6]
 [37 45]
 [58  5]
 [13 93]
 [26 12]
 [11 34]]
[2 3]
[110 123  78  94  25  54  56  90  25  32]


In [25]:
# Question 8 : Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
shape = (6, 7, 8)
flat_index = 99

index = np.unravel_index(flat_index, shape)
print("Index of the 100th element:", index)


Index of the 100th element: (np.int64(1), np.int64(5), np.int64(3))


In [28]:
# Question 9 : You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

# Input Format:

# A single line of input containing space separated numbers.

# Output Format:

# Print the reverse NumPy array with type float.

# Example 1:

# Input:

# 1 2 3 4 -8 -10
# Output:

# [-10.  -8.   4.   3.   2.   1.]





input_str = input()


arr = np.array(input_str.split(), dtype=float)


reversed_arr = arr[::-1]


print(reversed_arr)


[ 32.   2.  23. 432.  43.   3. 543.   6.   5.   4.   3.   2.   1.]


In [30]:
# Ques10: Count the number of elements of a numpy array.

arr = np.array([1,2,3,4])

elements_count = arr.size

print("elements_count :", elements_count)


elements_count : 4


In [31]:
# Ques11 : Softmax function
# Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.
def softmax(x):
    if not isinstance(x, np.ndarray) or x.ndim != 1:
        raise ValueError("Input must be a 1D NumPy array.")

    # For numerical stability, subtract max value
    e_x = np.exp(x - np.max(x))
    return e_x / np.sum(e_x)


In [32]:
# Example 1
arr1 = np.array([86.03331084, 37.7285648, 48.64908087, 87.16563062, 38.40852563, 37.20006318])
print(softmax(arr1))

# Example 2
arr2 = np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098, 68.82830233, 91.52064278])
print(softmax(arr2))


[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]
[4.57181033e-26 1.16249922e-20 7.73872594e-05 2.60358426e-05
 1.39571531e-10 9.99896577e-01]


In [34]:
# Question 12: Vertical stack
# Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.

# Example 1:

# Input:

# a= [[0 1 2 3 4]
#  [5 6 7 8 9]]

# b= [[1 1 1 1 1]
#  [1 1 1 1 1]]

def vertical_stack(*arrays):
    for array in arrays:
        if not isinstance(array , np.ndarray):
            raise valueError("All arrays must be numpy arrays")
            
        return np.vstack(arrays)


In [35]:
a = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]])

b = np.array([[1, 1, 1, 1, 1],
              [1, 1, 1, 1, 1]])

c = np.array([[0.10117373, 0.1677244,  0.73764059, 0.83166097, 0.48985695],
              [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

result = vertical_stack(a, b, c)
print(result)


[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


In [36]:
# Ques 13:Create a python function named date_array that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: 2022-12-6. The end date should be included and for simplicity, choose dates from a same year.
import numpy as np
from datetime import datetime

def date_array(start, end):
    if not (isinstance(start, str) and isinstance(end, str)):
        raise ValueError("Both start and end dates must be strings.")
    try:
        start_date = datetime.strptime(start, "%Y-%m-%d")
        end_date = datetime.strptime(end, "%Y-%m-%d")
    except ValueError:
        raise ValueError("Date format must be 'YYYY-MM-DD', e.g., '2022-12-6'")
    if start_date.year != end_date.year:
        raise ValueError("Dates must be from the same year.")
    
    dates = np.arange(start_date, end_date + np.timedelta64(1, 'D'), dtype='datetime64[D]')
    
    return dates.astype(str)


In [37]:
result = date_array(start='2020-09-15', end='2020-09-25')
print(result)


['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']


In [40]:
# Ques 14:  Subtract the mean of each row from a matrix.
matrix = np.arange(1,10).reshape(3,3)
print(matrix)
result = matrix- matrix.mean(axis=1 , keepdims=True)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [45]:
# Ques 15: Swap column-1 of array with column-2 in the array.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr[:, [0, 1]] = arr[:, [1, 0]]

print("Array after swapping column 1 and column 2:\n", arr)


Array after swapping column 1 and column 2:
 [[2 1 3]
 [5 4 6]
 [8 7 9]]


In [48]:
# Ques 16:  Replace odd elements in arrays with -1.
import numpy as np
arr = np.arange(1,11)
arr[arr % 2 != 0] = -1

print("Modified array:", arr)

Modified array: [-1  2 -1  4 -1  6 -1  8 -1 10]


In [49]:
# Ques 17: Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result = np.maximum(a,b)
print(Result)

[6 3 1 7 8]


In [50]:
# Ques 18: 
import numpy as np

arr1 = np.array([
    [2939, 1694, 6680, 8865, 2684],
    [4066, 4573,  327, 6525,  851],
    [5997, 7481, 2315, 5863, 9615],
    [7821, 1225, 9138, 1114, 4885],
    [7715, 8046, 9105, 3935, 3182],
    [8842, 4836, 2705, 3751, 3800],
    [4132, 1400, 7844, 9471, 7526],
    [2749, 2624, 6900, 1576, 7515]
])

alternate_columns = arr1[:, ::2]  
print("Alternate columns:\n", alternate_columns)


Alternate columns:
 [[2939 6680 2684]
 [4066  327  851]
 [5997 2315 9615]
 [7821 9138 4885]
 [7715 9105 3182]
 [8842 2705 3800]
 [4132 7844 7526]
 [2749 6900 7515]]


In [51]:
X_min = arr1.min()
X_max = arr1.max()

normalized_arr = (arr1 - X_min) / (X_max - X_min)
print("Normalized array:\n", normalized_arr)


Normalized array:
 [[0.28122308 0.14717916 0.68400086 0.91925065 0.2537683 ]
 [0.40256245 0.45714901 0.         0.66731266 0.05641688]
 [0.61046512 0.77024117 0.21403962 0.5960379  1.        ]
 [0.80684755 0.09668389 0.94864341 0.08473299 0.49074074]
 [0.79543497 0.83107235 0.94509044 0.38845823 0.30738587]
 [0.91677433 0.48546512 0.25602929 0.36864772 0.37392334]
 [0.40966839 0.11552541 0.80932386 0.98449612 0.77508613]
 [0.26076658 0.24730835 0.70768734 0.13447459 0.77390181]]


In [53]:
# Ques 19:  Write a function which will accept 2 arguments.
# First: A 1D numpy array arr

# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40


def nth_largest(arr, n):
    if not isinstance(arr, np.ndarray) or arr.ndim != 1:
        raise ValueError("First argument must be a 1D NumPy array.")
    if not isinstance(n, int) or n < 1 or n > len(arr):
        raise ValueError("Second argument must be an integer between 1 and the length of the array.")
    
    sorted_arr = np.sort(arr)[::-1]  
    return sorted_arr[n - 1]


In [55]:
arr = np.array([12, 34, 40, 7, 1, 0])

print(nth_largest(arr, 3))  
print(nth_largest(arr, 1))


12
40
