In [1]:
# creating numpy arrays 

In [2]:
#np.array 
import numpy as np 

np.array([1,2,3,4,5])
a  = np.array([1,2,3,4,5]) #--> 1D array 
print(a)
print(type(a))
b = np.array([[1,2,3],[4,5,6]]) #--> 2D array
print(b)
c = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(c.ndim)  # Output: 3
print(c)


[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
3
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [3]:
# dtype 

a =np.array([1,2,3] , dtype = 'float')
print(a)
b =np.array([1,2,3] , dtype = 'complex')
print(b)


[1. 2. 3.]
[1.+0.j 2.+0.j 3.+0.j]


In [4]:
# np.arange 
a = np.arange(1,11)
print(a)
b = np.arange(1,11,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [5]:
# with reshape 
np.arange(1,11).reshape(5,2) # 5 rows 2 columns 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [6]:
# np.ones and np.zeros 

np.ones((3,4) , dtype='int')
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
#np.random 
np.random.random((3,4))

array([[0.11358603, 0.40117368, 0.0477881 , 0.44340641],
       [0.79992342, 0.98931328, 0.65015348, 0.42650625],
       [0.57926706, 0.9734636 , 0.53643018, 0.37249376]])

In [9]:
# np.linspace 
np.linspace(-10 , 10 , 10) # (lower range , upper range , no of items)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [10]:
#np.identity 
np.identity(3)  # identity matrix of 3*3 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# in above all methods dtype can be used 

#### Array Attributes

In [12]:
a1 = np.arange(10)  # can be called as vector
a2 = np.arange(12, dtype=float).reshape(3,4) #matrix
a3 = np.arange(8).reshape(2,2,2) # tensor

In [13]:
a1.ndim # 1 (dimesions)

1

In [14]:
a2.ndim

2

In [15]:
a3.ndim

3

In [16]:
a1.shape

(10,)

In [17]:
a2.shape

(3, 4)

In [18]:
print(a3.shape)
print(a3)

(2, 2, 2)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [19]:
# size 
a3.size # no items 

8

In [20]:
a2.size

12

In [21]:
# itemsize ( tells how much memory the particular item takes)
a3.itemsize

8

In [22]:
a2.itemsize

8

In [23]:
a1.itemsize

8

In [24]:
a4 = np.arange(10 , dtype=np.int32)
print(a4)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
a4.itemsize

4

##### Changing DataType

In [26]:
# astype 
a3 

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
a3.dtype

dtype('int64')

In [28]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

#### Array Operations

In [29]:
a1 = np.arange(12).reshape(3,4)
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
# scaler operations 


# arithmetic 
print(a1*2 )
print(a1**2 )
print(a1-2 )
print(a1+2 )

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [31]:
# relational 
a2 == 5 

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [32]:
# relational 
a2 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [33]:
# vector operations  --> in between two numpy arrays 
# arithmetic
a1 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [35]:
a1 +a2  # because shape of both is same 

array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.]])

In [36]:
a1-a2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
a1*a2

array([[  0.,   1.,   4.,   9.],
       [ 16.,  25.,  36.,  49.],
       [ 64.,  81., 100., 121.]])

In [38]:
a1**a2

array([[1.00000000e+00, 1.00000000e+00, 4.00000000e+00, 2.70000000e+01],
       [2.56000000e+02, 3.12500000e+03, 4.66560000e+04, 8.23543000e+05],
       [1.67772160e+07, 3.87420489e+08, 1.00000000e+10, 2.85311671e+11]])

#### Array Functions 

In [39]:
a1= np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[86., 56., 34.],
       [ 4., 24., 83.],
       [94., 79., 58.]])

In [40]:
# max/min/sum/prod 
np.max(a1)

np.float64(94.0)

In [41]:
np.min(a1)

np.float64(4.0)

In [42]:
np.sum(a1)

np.float64(518.0)

In [43]:
np.prod(a1)

np.float64(561949978791936.0)

In [44]:
# 0--> col 
# 1--> row
np.max(a1,axis=1)

array([86., 83., 94.])

In [45]:
np.max(a1 ,axis = 0)

array([94., 79., 83.])

In [46]:
# mean/median/std/var
np.mean(a1, axis =1)

array([58.66666667, 37.        , 77.        ])

In [47]:
np.std(a1, axis =1)


array([21.31248982, 33.53605025, 14.76482306])

In [48]:
np.var(a1, axis =1)


array([ 454.22222222, 1124.66666667,  218.        ])

In [49]:
np.var(a1, axis =1)


array([ 454.22222222, 1124.66666667,  218.        ])

In [50]:
## trignometric functions  
np.sin(a1)

array([[-0.92345845, -0.521551  ,  0.52908269],
       [-0.7568025 , -0.90557836,  0.96836446],
       [-0.24525199, -0.44411267,  0.99287265]])

In [51]:
# dot product 
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
print(a2.dot(a3))
print(a3.dot(a2))

[[114 120 126]
 [378 400 422]
 [642 680 718]]
[[164 203 242 281]
 [200 248 296 344]
 [236 293 350 407]
 [272 338 404 470]]


In [52]:
# log and exponents  
np.log(a1)

array([[4.4543473 , 4.02535169, 3.52636052],
       [1.38629436, 3.17805383, 4.41884061],
       [4.54329478, 4.36944785, 4.06044301]])

In [53]:
np.exp(a1)

array([[2.23524660e+37, 2.09165950e+24, 5.83461743e+14],
       [5.45981500e+01, 2.64891221e+10, 1.11286375e+36],
       [6.66317622e+40, 2.03828107e+34, 1.54553894e+25]])

In [54]:
# round/floor/ceil 

np.random.random((2,3))*100

array([[86.39576315, 38.68115408, 82.3356941 ],
       [28.78747635, 83.08545826, 13.16562951]])

In [55]:
np.round(np.random.random((2,3))*100)

array([[74.,  4., 20.],
       [29., 51., 26.]])

In [56]:
np.floor(np.random.random((2,3))*100)


array([[40., 77., 87.],
       [49., 56., 62.]])

In [57]:
np.ceil(np.random.random((2,3))*100)


array([[36., 23., 20.],
       [51., 18.,  8.]])

#### Indexing and slicing

In [58]:
a1= np.arange(10)
a2= np.arange(12).reshape(3,4)
a3= np.arange(8).reshape(2,2,2)

In [59]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [64]:
print(a1[-1])

9


In [63]:
print(a1[0])

0


In [66]:
print(a2[1,2]) #row col

6


In [67]:
print(a2[2,3])

11


In [68]:
print(a2[1,0])

4


In [70]:
print(a3[1 ,0,1])

5


In [71]:
print(a3[0 ,1,0])

2


In [72]:
print(a3[0 ,0,0])

0


In [74]:
print(a3[1,1,0])

6


In [75]:
# slicing 
a1[2:5]

array([2, 3, 4])

In [76]:
a1[2:5:2]

array([2, 4])

In [78]:
a2[0, :]

array([0, 1, 2, 3])

In [79]:
a2[: ,2]

array([ 2,  6, 10])

In [80]:
a2[1: , 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [81]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [87]:
a2[::2 ,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [92]:
a2[1 ,::3]

array([4, 7])

In [97]:
a2[0:2 ,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [99]:
a2[0:2 ,1::2]

array([[1, 3],
       [5, 7]])

In [102]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [103]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [104]:
a3[1:3:2]

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [105]:
a3[::2]


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [115]:
a3[0,1,:]

array([3, 4, 5])

In [120]:
a3[1,: ,1 ]

array([10, 13, 16])

In [122]:
a3[2,1: ,1:]

array([[22, 23],
       [25, 26]])

In [132]:
a3[0::2 ,0 , 0::2 ]

array([[ 0,  2],
       [18, 20]])

#### Iterating

In [133]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [135]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [137]:
for i in range (len(a1)):
    print(i)


0
1
2
3
4
5
6
7
8
9


In [138]:
for i in a1:
    print(i) 

0
1
2
3
4
5
6
7
8
9


In [139]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [141]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [147]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [148]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [149]:
# transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [150]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [151]:
a2 = a2.T

In [152]:
print(a2)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [153]:
a2.T

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# ravel
a2.ravel()  #converts into 1D array

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [156]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

#### Stacking 

In [158]:
# horizontal Stacking 
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4)
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [160]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [161]:
np.hstack((a4,a5,a4))


array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [ ]:
np.hstack((a4,a5,a4,a5))


array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [165]:
#vertical stacking

np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### Spilitting

In [167]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [166]:
# horizontal spilitting  
np.hsplit(a4 ,2 ) # array and part --> inputs 

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [168]:
np.hsplit(a4 ,4) 

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [169]:
np.hsplit(a4 ,3) 

ValueError: array split does not result in an equal division

In [170]:
# vertical spilitting 

a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [171]:
np.vsplit(a5 ,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [173]:
print(np.vsplit(a5 ,3))

[array([[12, 13, 14, 15]]), array([[16, 17, 18, 19]]), array([[20, 21, 22, 23]])]
