In [1]:
# np.sort() --> return the sorted array 

import numpy as np 

a = np.random.randint(1,100,15)
print(a)

[31 30 75 80 48 33  1 73 11 89 16 71 31 15 73]


In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
print(b)

[[35 78 25  7]
 [56 66 84 87]
 [35 45 67 38]
 [47  3 23 17]
 [21 95 99 43]
 [46 86 42 22]]


In [3]:
print(np.sort(a),"--> sorted Array")

[ 1 11 15 16 30 31 31 33 48 71 73 73 75 80 89] --> sorted Array


In [4]:
np.sort(b) #default sorted by row 

array([[ 7, 25, 35, 78],
       [56, 66, 84, 87],
       [35, 38, 45, 67],
       [ 3, 17, 23, 47],
       [21, 43, 95, 99],
       [22, 42, 46, 86]], dtype=int32)

In [5]:
np.sort(b , axis=0) # sorted by column

array([[21,  3, 23,  7],
       [35, 45, 25, 17],
       [35, 66, 42, 22],
       [46, 78, 67, 38],
       [47, 86, 84, 43],
       [56, 95, 99, 87]], dtype=int32)

In [6]:
np.sort(a)[::-1] # sort in decreasing order

array([89, 80, 75, 73, 73, 71, 48, 33, 31, 31, 30, 16, 15, 11,  1],
      dtype=int32)

In [7]:
# np.append() --> appends values along the mentioned axis at the end of the array


In [8]:
print(a)
np.append(a,200)

[31 30 75 80 48 33  1 73 11 89 16 71 31 15 73]


array([ 31,  30,  75,  80,  48,  33,   1,  73,  11,  89,  16,  71,  31,
        15,  73, 200])

In [9]:
print(b)
np.append(b, np.ones((b.shape[0] ,1)) , axis = 1)

[[35 78 25  7]
 [56 66 84 87]
 [35 45 67 38]
 [47  3 23 17]
 [21 95 99 43]
 [46 86 42 22]]


array([[35., 78., 25.,  7.,  1.],
       [56., 66., 84., 87.,  1.],
       [35., 45., 67., 38.,  1.],
       [47.,  3., 23., 17.,  1.],
       [21., 95., 99., 43.,  1.],
       [46., 86., 42., 22.,  1.]])

In [10]:
# np.concatenate() --> concatenate a sequence of arrays along an existing axis.
c = np.arange(6).reshape(2,3)
d= np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [11]:
np.concatenate((c,d), axis = 0) # row wise 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.concatenate((c,d), axis = 1) # column wise

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [13]:
# np.unique() --> we can get the unique values from an array given as parameter in np.unique() method
e= np.array([1,1,2,2,3,3,4,4,5,5,6,6])
f= np.array([[1,2,3,1],[1,2,3,2]])
print(e)
print(f)

[1 1 2 2 3 3 4 4 5 5 6 6]
[[1 2 3 1]
 [1 2 3 2]]


In [14]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [15]:
# np.expand_dims() --> we can get the expanded dimension of an array 
a

array([31, 30, 75, 80, 48, 33,  1, 73, 11, 89, 16, 71, 31, 15, 73],
      dtype=int32)

In [16]:
test = np.expand_dims(a, axis=0) #--> producing 2D array
print(test)
print(test.shape)

[[31 30 75 80 48 33  1 73 11 89 16 71 31 15 73]]
(1, 15)


In [17]:
test2 = np.expand_dims(a, axis=1) 
print(test2)
print(test2.shape)

[[31]
 [30]
 [75]
 [80]
 [48]
 [33]
 [ 1]
 [73]
 [11]
 [89]
 [16]
 [71]
 [31]
 [15]
 [73]]
(15, 1)


In [18]:
# np.where() --> return indices the elements in array where given condition is satisfied 
print(a)

[31 30 75 80 48 33  1 73 11 89 16 71 31 15 73]


In [19]:
# find all indices with value greater than 50 
np.where(a > 50)

(array([ 2,  3,  7,  9, 11, 14]),)

In [20]:
# replace all indices with value greater than 50

# np.where(condition, true, false)  --> syntax
np.where(a>50,0,a)

array([31, 30,  0,  0, 48, 33,  1,  0, 11,  0, 16,  0, 31, 15,  0],
      dtype=int32)

In [21]:
np.where(a%2==0 , 0, a)

array([31,  0, 75,  0,  0, 33,  1, 73, 11, 89,  0, 71, 31, 15, 73],
      dtype=int32)

In [22]:
# np.argmax() --> return the indices of the max element of the array in a particular axis
a

array([31, 30, 75, 80, 48, 33,  1, 73, 11, 89, 16, 71, 31, 15, 73],
      dtype=int32)

In [23]:
np.argmax(a , axis=0)

np.int64(9)

In [24]:
np.argmax(a)

np.int64(9)

In [25]:
print(b)

[[35 78 25  7]
 [56 66 84 87]
 [35 45 67 38]
 [47  3 23 17]
 [21 95 99 43]
 [46 86 42 22]]


In [26]:
np.argmax(b, axis=0) #columnwise 

array([1, 4, 4, 1])

In [27]:
np.argmax(b, axis=0) #rowwise 

array([1, 4, 4, 1])

In [28]:
# np.argmin()
np.argmin(b, axis=0)

array([4, 3, 3, 0])

In [29]:
# np.cumsum() --> used to compute cumulative sum of array elements over a given axis
print(a)

[31 30 75 80 48 33  1 73 11 89 16 71 31 15 73]


In [30]:
np.cumsum(a)    

array([ 31,  61, 136, 216, 264, 297, 298, 371, 382, 471, 487, 558, 589,
       604, 677])

In [31]:
print(b)

[[35 78 25  7]
 [56 66 84 87]
 [35 45 67 38]
 [47  3 23 17]
 [21 95 99 43]
 [46 86 42 22]]


In [32]:
np.cumsum(b) ## flatten the array then apply cummulative sum

array([  35,  113,  138,  145,  201,  267,  351,  438,  473,  518,  585,
        623,  670,  673,  696,  713,  734,  829,  928,  971, 1017, 1103,
       1145, 1167])

In [33]:
np.cumsum(b , axis=0) # columnwise cummulative sum

array([[ 35,  78,  25,   7],
       [ 91, 144, 109,  94],
       [126, 189, 176, 132],
       [173, 192, 199, 149],
       [194, 287, 298, 192],
       [240, 373, 340, 214]])

In [34]:
np.cumsum(b , axis=1) # columnwise cummulative sum

array([[ 35, 113, 138, 145],
       [ 56, 122, 206, 293],
       [ 35,  80, 147, 185],
       [ 47,  50,  73,  90],
       [ 21, 116, 215, 258],
       [ 46, 132, 174, 196]])

In [35]:
# np.cumprod() 
np.cumprod(a)

array([                 31,                 930,               69750,
                   5580000,           267840000,          8838720000,
                8838720000,        645226560000,       7097492160000,
           631676802240000,   10106828835840000,  717584847344640000,
       3798386193974288384, 1635560688485670912, 8715465817196666880])

In [36]:
# np.percentile() --> used to compute the nth percentile
print(a)
np.percentile(a , 100)  # 100 percentile

[31 30 75 80 48 33  1 73 11 89 16 71 31 15 73]


np.float64(89.0)

In [37]:
np.percentile(a, 50)

np.float64(33.0)

In [38]:
np.median(a)

np.float64(33.0)

In [39]:
#np.histogram() 

np.histogram(a , bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 3, 0, 4, 1, 0, 0, 4, 2, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [40]:
# np.corrcoef() --> return pearson product-moment correlation coefficients.

In [41]:
salary = np.array([20000 , 40000, 25000 , 35000, 60000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary , experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [42]:
# np.isin() --> we can see that one array having values are checked in a different numpy array having different elements with different sizes

In [43]:
print(a)

[31 30 75 80 48 33  1 73 11 89 16 71 31 15 73]


In [44]:
items  = [10,20,30,40,50,60,70,80,90,100]

In [45]:
np.isin(a ,items)

array([False,  True, False,  True, False, False, False, False, False,
       False, False, False, False, False, False])

In [46]:
a[np.isin(a ,items)]

array([30, 80], dtype=int32)

In [47]:
# np.flip() --> reverses the order of array elements along the specified axis, preventing the shape of array 
print(a)
print(np.flip(a))

[31 30 75 80 48 33  1 73 11 89 16 71 31 15 73]
[73 15 31 71 16 89 11 73  1 33 48 80 75 30 31]


In [48]:
print(b)
print(np.flip(b))  # row fliping + col flipiing 

[[35 78 25  7]
 [56 66 84 87]
 [35 45 67 38]
 [47  3 23 17]
 [21 95 99 43]
 [46 86 42 22]]
[[22 42 86 46]
 [43 99 95 21]
 [17 23  3 47]
 [38 67 45 35]
 [87 84 66 56]
 [ 7 25 78 35]]


In [49]:
print(b)
print(np.flip(b ,axis =0 ) )

[[35 78 25  7]
 [56 66 84 87]
 [35 45 67 38]
 [47  3 23 17]
 [21 95 99 43]
 [46 86 42 22]]
[[46 86 42 22]
 [21 95 99 43]
 [47  3 23 17]
 [35 45 67 38]
 [56 66 84 87]
 [35 78 25  7]]


In [50]:
# np.put() --> function replaces specific elements of an array with given values of p_array . array indexed works on flattened array. 
print(a)
np.put(a,[0,1],[110,530]) # changes in main array --> permanent changes 
print(a)

[31 30 75 80 48 33  1 73 11 89 16 71 31 15 73]
[110 530  75  80  48  33   1  73  11  89  16  71  31  15  73]


In [51]:
# np.delete() --> returns a new array with deletion of sub-arrays along with mentioned axis
np.delete(a, [0,2,4])  # deletes elements on the indices in an array

array([530,  80,  33,   1,  73,  11,  89,  16,  71,  31,  15,  73],
      dtype=int32)

In [52]:
print(a)

[110 530  75  80  48  33   1  73  11  89  16  71  31  15  73]


In [53]:
# set functions  
 # np.union1d
 #np.intersect1d
 #np.setdiff1d
 #np.setxor1d
 #np.in1d

In [54]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [55]:
np.intersect1d(m,n)

array([3, 4, 5])

In [56]:
np.setdiff1d(m,n)

array([1, 2])

In [57]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [58]:
np.in1d(m,10)

C:\Users\singh\AppData\Local\Temp\ipykernel_16420\3337556509.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,10)


array([False, False, False, False, False])

In [59]:
# numpy.clip() --> function is used to clip(limit) the values in an array
print(a)

[110 530  75  80  48  33   1  73  11  89  16  71  31  15  73]


In [60]:
np.clip(a , a_min=20, a_max=100)

array([100, 100,  75,  80,  48,  33,  20,  73,  20,  89,  20,  71,  31,
        20,  73], dtype=int32)

In [ ]:
# np.swapaxes # np.uniform # np.count_nonzero #np.tile() #np.repeat() # np.allclose and equals 